providers = ["python"]

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["python3", "libjpeg", "zlib", "libpng", "libwebp", "gcc"]

[phases.install]
cmds = ["python3 -m pip install -r backend/requirements.txt"]

[start]
cmd = "bash start.sh"
